<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKApxOjk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKApxOjk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKApxOjk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKApxOjk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKApxOjk\App_KernelDevDebugContainer([
    'container.build_hash' => 'KApxOjk',
    'container.build_id' => 'f2cdd630',
    'container.build_time' => 1711028455,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKApxOjk');
