<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZQDnrGx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQDnrGx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZQDnrGx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZQDnrGx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZQDnrGx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZQDnrGx',
    'container.build_id' => '797423cc',
    'container.build_time' => 1710805423,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQDnrGx');
