<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1kfNin\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1kfNin/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1kfNin.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1kfNin\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO1kfNin\App_KernelDevDebugContainer([
    'container.build_hash' => 'O1kfNin',
    'container.build_id' => 'd3525c68',
    'container.build_time' => 1712124492,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1kfNin');
