<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKCZrLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKCZrLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKCZrLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKCZrLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXKCZrLx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XKCZrLx',
    'container.build_id' => 'e541d9a8',
    'container.build_time' => 1710512643,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKCZrLx');
